### ISSUE TITLE
TestFSNewInventoryTransaction fails

### ISSUE THREAD

**Issue by ssmall** [GoogleCloudPlatform/cloud-run-anthos-reference-web-app#10]
See https://github.com/GoogleCloudPlatform/cloud-run-anthos-reference-web-app/pull/3#discussion_r412566469

_Originally posted by @ssmall in https://github.com/GoogleCloudPlatform/cloud-run-anthos-reference-web-app/pull/3/files_

**Comment by josueetcom** [comment]
This no longer seems to be an issue on my workstation when I run against the Cloud SDK Cloud Firestore Emulator using `gcloud`. However, the docker based Firestore emulator does still fail the tests so it seems this was fixed recently, perhaps in the [Cloud SDK 290.0.0 release](https://groups.google.com/forum/#!searchin/google-cloud-sdk-announce/Cloud$20Firestore$20emulator%7Csort:date/google-cloud-sdk-announce/-MQxHknpUSc/YF_RyOxJBAAJ) as it is the only recent release with Cloud Firestore emulator updates. 

I will look into fixing the docker container issue
