### ISSUE TITLE
test-webui makefile target failing locally

### ISSUE THREAD

**Issue by josueetcom** [GoogleCloudPlatform/cloud-run-anthos-reference-web-app#95]
Running  `make test-webui` locally fails with the following:
```
"Get codecov token": ERROR: (gcloud.secrets.versions.access) PERMISSION_DENIED: Permission 'secretmanager.versions.access' denied for resource 'projects/sixtor-0526/secrets/codecov-token/versions/latest' (or it may not exist).
```

This seems to be due to adding [code coverage](https://github.com/GoogleCloudPlatform/cloud-run-anthos-reference-web-app/blob/master/webui/cloudbuild-test.yaml#L52-L71) to the webui test in recent changes. It seems to expect a secret that exists in the project used by GitHub but not necessarily in the local developer's project.

**Comment by ssmall** [comment]
Fixed in #106
